// <auto-generated />
using System;
using AstroCrud.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstroCrud.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402180055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AstroCrud.Api.Models.ObservacionAstronomica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaObservacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjetoCeleste")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelescopioUsado")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ObservacionesAstronomicas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Observación nocturna con cielo despejado.",
                            EsVisible = true,
                            FechaObservacion = new DateTime(2026, 3, 20, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            ObjetoCeleste = "Luna",
                            TelescopioUsado = "Celestron 130EQ",
                            Titulo = "Luna llena sobre la ciudad",
                            Ubicacion = "Santo Domingo"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Se pudieron observar varias lunas galileanas.",
                            EsVisible = true,
                            FechaObservacion = new DateTime(2026, 3, 24, 21, 15, 0, 0, DateTimeKind.Unspecified),
                            ObjetoCeleste = "Júpiter",
                            TelescopioUsado = "Sky-Watcher 150P",
                            Titulo = "Júpiter y sus lunas",
                            Ubicacion = "La Vega"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
